services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    image: ${AIRFLOW_IMAGE_NAME}
    depends_on: [postgres]
    entrypoint: /bin/bash
    command:
      - -c
      - >
        airflow db init &&
        airflow users create --username admin --password admin123
        --firstname Admin --lastname User --role Admin --email admin@example.com
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    user: "${AIRFLOW_UID:-50000}"
    volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data

  webserver:
    image: ${AIRFLOW_IMAGE_NAME}
    depends_on: [airflow-init]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: webserver
    ports: ["8080:8080"]
    user: "${AIRFLOW_UID:-50000}"
    volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data

  scheduler:
    image: ${AIRFLOW_IMAGE_NAME}
    depends_on: [webserver]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: scheduler
    user: "${AIRFLOW_UID:-50000}"
    volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data

volumes:
  pgdata: